FROM python:3

#RUN pip install --upgrade pip
#
## RUN pip install -U openai-whisper
#
#RUN apt update && apt install -y ffmpeg
#
#RUN pip install \
#    torch==2.3.1+cpu \
#    torchaudio==2.3.1+cpu \
#    -f https://download.pytorch.org/whl/torch_stable.html
#
#RUN pip install whisper-timestamped
