name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v4

      - name: Echo Docker Username
        run: |
          echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: docker
          file: docker/Dockerfile
          push: true
          tags: kartaltabak/whisper:latest
